[workspace]
authors = ["Brian Mc Donald <brian@brianmcdonald.me>"]
channels = ["conda-forge"]
name = "base"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pip = "*"
conda = "*"
mamba = ">=1.5.8"
geopandas = "*"
hvplot = "*"
itables = "*"
lonboard = "*"
matplotlib = ">=3.10.3,<4"
polars = ">=1.30.0,<2"
pydeck = "*"
scipy = ">=1.15.2,<2"
jupyter = ">=1.1.1,<2"
